final_pjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('movies.urls')),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('all/', views.movie_all, name='movie_all'),  # 영화 리스트
    path('search/', views.search, name='search'), # 검색 기능
    path('community/', views.article_list, name='article_list'),  # 게시판 (모든 글 리스트)
    path('<int:movie_pk>/', views.movie_detail, name='movie_detail'),  # 영화 디테일이자 해당 영화와 관련된 글 리스트
    path('<int:movie_pk>/like/', views.movie_like, name='movie_like'), # 영화 좋아요 버튼
    path('<int:movie_pk>/create/', views.article_create, name='article_create'),  # 글 작성
    path('articles/<int:article_pk>/', views.article_detail, name='article_detail'),  # 글 디테일이자 댓글 리스트
    path('articles/<int:article_pk>/delete/', views.article_delete, name='article_delete'),  # 글 삭제
    path('articles/<int:article_pk>/update/', views.article_update, name='article_update'),  # 글 수정
    path('articles/<int:article_pk>/create/', views.comment_create, name='comment_create'),  # 댓글 작성
    path('<int:article_pk>/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),  # 댓글 삭제
    path('genres/',views.genre_all,name='genre_all'), # 모든 장르
    path('genres/<int:genre_pk>/',views.genre_detail, name='genre_detail'), # 특정 장르
    path('recommend/',views.recommend,name='recommend'), # 추천
    path('recommend/random/',views.recommend_random,name='recommend_random'), # 랜덤 추천
    path('recommend/<int:genre_pk>/', views.recommend_genre, name='recommend_genre'), # 결과로 나온 장르에서 영화 고르기
    path('worldcup/',views.worldcup,name='worldcup'), # 월드컵
    path('worldcup/<int:genre_pk>/<int:round_num>/', views.start_worldcup, name='start_worldcup'), # 월드컵 데이터 가져오기
    path('victory/<int:movie_pk>/',views.victory,name='victory'), # 월드컵 우승 올리기
    path('now/',views.movie_now,name='movie_now'), # 지금 상영작
    path('upcoming/',views.movie_upcoming,name='movie_upcoming'), # 상영 예정작
]

movies/models.py
from django.db import models
from django.conf import settings
# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=100)

class Movie(models.Model):
    poster_path = models.TextField()
    adult = models.BooleanField()
    overview = models.TextField()
    release_date = models.DateField()
    genres = models.ManyToManyField(Genre,related_name='movies')
    original_title = models.CharField(max_length=300)
    original_language = models.CharField(max_length=20)
    title = models.CharField(max_length=500)
    backdrop_path = models.TextField()
    popularity = models.FloatField()
    vote_count = models.IntegerField()
    video = models.BooleanField()
    vote_average = models.FloatField()
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_movies')
    world_cup = models.IntegerField(default=0)

class Article(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    rank = models.IntegerField(default=10)
    title = models.CharField(max_length=200)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

movies/forms.py
from django import forms
from .models import Article, Comment

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'rank', 'content']
        widgets = {
            'title' : forms.TextInput(attrs={'class':'col-12 form-control', 'placeholder': '리뷰제목을 입력해주세요'}),
            'rank': forms.Select(choices=[[i,i] for i in range(0,11)]),
            'content' : forms.Textarea(attrs={'class':'col-12 form-control', 'placeholder':'내용을 입력해주세요','cols':100, 'rows':10})
        }
        labels = {
            'title': ('리뷰 제목'),
            'rank': ('별점'),
            'content': ('내용'),
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content': forms.Textarea(attrs={'placeholder': '댓글을 입력해주세요!', 'rows':3})
        }
        labels = {
            'content': ('')
        }

movies/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.conf import settings
from django.http import JsonResponse
from django.core.paginator import Paginator
from django.db.models import Count, Q
from django.contrib import messages
from .models import Movie, Genre, Article, Comment
from .forms import ArticleForm, CommentForm
import requests
import random

# Create your views here.
def index(request):
    api_key = settings.TMDB_KEY
    data = requests.get('https://api.themoviedb.org/3/movie/now_playing?api_key='+api_key+'&language=ko-KR&page=1&region=KR').json()
    recommend_movies = data['results'][:10]
    pop_movies = Movie.objects.exclude(id=664413).order_by('-popularity')[:6]
    vote_movies = Movie.objects.exclude(id=664413).order_by('-vote_average')[:6]
    articles = Article.objects.order_by('-pk')[:10]
    users_movies = Movie.objects.annotate(q_count=Count('like_users')).order_by('-q_count')[:6]
    random_movie = requests.get('https://api.themoviedb.org/3/movie/upcoming?api_key='+api_key+'&language=ko-KR&page=1&region=KR').json()
    random_movie = random.choice(random_movie['results'])
    api_key = settings.API_SECRET_KEY
    context = {
        'recommend_movies': recommend_movies,
        'pop_movies': pop_movies,
        'vote_movies': vote_movies,
        'articles': articles,
        'users_movies': users_movies,
        'random_movie': random_movie,
        'api_key': api_key
    }
    return render(request,'movies/index.html',context)

def search(request):
    if request.method == 'POST':
        search_value = request.POST['search_value']
        if search_value == '':
            messages.warning(request,'검색창에 검색어를 입력해주세요!')
            return redirect('movies:index')
        else:
            movies = Movie.objects.filter(title__contains=search_value).distinct()
            articles = Article.objects.filter(Q(title__contains=search_value)|Q(content__contains=search_value)).distinct()
            context = {
                'movies': movies,
                'articles': articles
            }
            return render(request,'movies/search.html',context)
    else:
        messages.warning(request,'검색창을 이용해주세요! 💻')
        return redirect('movies:index')

def movie_all(request):
    sort = request.GET.get('sort','')
    if sort == 'vote':
        movies = Movie.objects.annotate(like_count=Count('like_users')).order_by('-vote_average')
    elif sort == 'pop':
        movies = Movie.objects.annotate(like_count=Count('like_users')).order_by('-popularity')
    elif sort == 'likes':
        movies = Movie.objects.annotate(like_count=Count('like_users')).order_by('-like_count')
    else:
        movies = Movie.objects.annotate(like_count=Count('like_users')).order_by('-release_date')
    genres = Genre.objects.order_by('name')
    paginator = Paginator(movies, 12)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'movies': movies,
        'genres': genres,
        'page_obj': page_obj,
    }
    return render(request,'movies/movie_all.html', context)

def article_list(request):
    articles = Article.objects.order_by('-pk')
    paginator = Paginator(articles,20)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'articles': articles,
        'page_obj': page_obj
    }
    return render(request,'articles/article_all.html',context)

def movie_detail(request, movie_pk):
    movie = get_object_or_404(Movie.objects.annotate(like_count=Count('like_users')).prefetch_related('article_set'),pk=movie_pk)
    api_key = settings.API_SECRET_KEY
    tmdb_key = settings.TMDB_KEY
    score = 0
    people = 0
    for i in movie.article_set.all():
        score += i.rank
        people += 1
    if people == 0:
        avg_rank = None
    else:
        avg_rank = round(score/people,1)
    context = {
        'movie': movie,
        'api_key': api_key,
        'avg_rank': avg_rank,
        'tmdb_key': tmdb_key
    }
    return render(request, 'movies/movie_detail.html', context)

def movie_like(request, movie_pk):
    if request.user.is_authenticated:
        movie = get_object_or_404(Movie,pk=movie_pk)
        logined = True
        if movie.like_users.filter(id=request.user.pk).exists():
            like = False
            movie.like_users.remove(request.user)
            like_people = len(movie.like_users.all())
        else:
            like = True
            movie.like_users.add(request.user)
            like_people = len(movie.like_users.all())
    else:
        logined = False
        like = False
        like_people = 0
    return JsonResponse({'logined':logined,'like':like,'like_people':like_people})

def article_create(request, movie_pk):
    if request.user.is_anonymous:
        messages.warning(request,'로그인을 해주세요 🙇')
        return redirect('accounts:login')
    else:
        if request.method == 'POST':
            form = ArticleForm(request.POST)
            if form.is_valid():
                movie = get_object_or_404(Movie,pk=movie_pk)
                article = form.save(commit=False)
                article.user = request.user
                article.movie = movie
                article.save()
                return redirect('movies:article_detail', article.pk)
        else:
            form = ArticleForm()
        context = {'form':form}
        return render(request,'articles/create.html',context)

def article_detail(request, article_pk):
    article = get_object_or_404(Article.objects.prefetch_related('comment_set'),pk=article_pk)
    form = CommentForm()
    context = {
        'article': article,
        'form': form
    }
    return render(request,'articles/detail.html',context)

def article_delete(request, article_pk):
    if request.user.is_anonymous:
        messages.warning(request,'이런 로그인을 깜빡하셨군요 😋')
        return redirect('accounts:login')
    article = get_object_or_404(Article,pk=article_pk)
    if request.user != article.user:
        messages.error(request,'다른 유저의 글은 삭제 못해요! 😡')
        return redirect('movies:article_detail',article.pk)
    else:
        if request.method == 'POST':
            article.delete()
            messages.success(request,'성공적으로 삭제 되었습니다! 👍')
            return redirect('movies:index')
        else:
            messages.error(request,'지정한 방식으로 삭제를 부탁드립니다 😭')
            return redirect('movies:article_detail',article.pk)


def article_update(request, article_pk):
    if request.user.is_anonymous:
        messages.warning(request,'이런 로그인을 깜빡하셨군요 😋')
        return redirect('accounts:login')
    article = get_object_or_404(Article,pk=article_pk)
    if article.user != request.user:
        messages.error(request,'다른 유저의 글은 수정할 수가 없습니다! 👿')
        return redirect('movies:article_detail',article.pk)
    else:
        if request.method == 'POST':
            form = ArticleForm(request.POST, instance=article)
            if form.is_valid():
                form.save()
                return redirect('movies:article_detail',article.pk)
        else:
            form = ArticleForm(instance=article)
        context = {'form': form }
        return render(request,'articles/create.html',context)

def comment_create(request, article_pk):
    if request.user.is_anonymous:
        messages.error(request,'로그인을 하고 댓글을 써주시길 바랍니다. 😇')
        return redirect('accounts:login')
    else:
        if request.method == 'POST':
            article = get_object_or_404(Article,pk=article_pk)
            form = CommentForm(request.POST)
            if form.is_valid():
                comment = form.save(commit=False)
                comment.user = request.user
                comment.article = article
                comment.save()
                return redirect('movies:article_detail', article.pk)
        else:
            messages.error(request,'댓글작성은 어떻게 들어오셨나요? 🤔')
            return redirect('movies:article_detail', article.pk)

def comment_delete(request, article_pk, comment_pk):
    if request.user.is_anonymous:
        messages.warning(request,'로그인을 하고 댓글삭제를 요청해주세요! 😵')
        return redirect('movies:article_detail',article_pk)
    comment = get_object_or_404(Comment, pk=comment_pk)
    if comment.user != request.user:
        messages.error(request,'남의 댓글은 삭제하실 수가 없는데 뭘 하시는 거죠? 🤔')
        return redirect('movies:article_detail',article_pk)
    else:
        if request.method == 'POST':
            comment.delete()
            messages.success(request,'성공적으로 댓글이 삭제되었습니다!')
        else:
            messages.warning(request,'정해진 방식으로 요청을 보내주세요! 😟')
        return redirect('movies:article_detail',article_pk)

def genre_all(request):
    genres = Genre.objects.all()
    context = {
        'genres': genres
    }
    return render(request,'movies/genre_all.html',context)

def genre_detail(request,genre_pk):
    genre_on = get_object_or_404(Genre,pk=genre_pk)
    sort = request.GET.get('sort','')
    if sort == 'vote':
        movies =  genre_on.movies.annotate(like_count=Count('like_users')).order_by('-vote_average')
    elif sort == 'pop':
        movies =  genre_on.movies.annotate(like_count=Count('like_users')).order_by('-popularity')
    elif sort == 'likes':
        movies =  genre_on.movies.annotate(like_count=Count('like_users')).order_by('-like_count')
    else:
        movies =  genre_on.movies.annotate(like_count=Count('like_users')).order_by('-release_date')
    paginator = Paginator(movies, 12)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    genres = Genre.objects.order_by('name')
    context = {
        'movies': movies,
        'page_obj': page_obj,
        'genres': genres,
        'genre_on': genre_on
    }
    return render(request,'movies/movie_all.html', context)

def recommend(request):
    weather_key = settings.WEATHER_KEY
    genres = Genre.objects.all()
    context = {
        'weather_key': weather_key,
        'genres': genres
    }

movies/templates/movies/genre_all.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %} 모든 장르 {% endblock %}

{% block content %}
<div class="container">
  {% for genre in genres %}
  <hr>
  <button type="button" class="btn btn-outline-primary btn-lg" data-toggle="modal" data-target="#modal{{genre.pk}}">
    {{ genre.name }}
  </button>

  <div class="modal fade" id="modal{{genre.pk}}" tabindex="-1" role="dialog" aria-labelledby="modal{{genre.pk}}Label" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="modal{{genre.pk}}Label">{{ genre.name }}</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <h2>대표 영화</h2>
          {% for movie in genre.movies.all|slice:":1" %}
          <img class="my-3" src="https://image.tmdb.org/t/p/w342/{{movie.poster_path}}">
          {% endfor %}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">닫기</button>
          <a class="btn btn-primary" href="{% url 'movies:genre_detail' genre.pk %}">장르 영화 목록</a>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}

movies/templates/movies/movie_all.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load bootstrap_pagination %}

{% block css %}
<style>
  h1 {
    font-family: 'Gugi', cursive; 
    color: crimson;
    background-color: #f8f9fa;
  }
  .form-control {
    cursor: pointer;
  }
  ul.pagination {
    justify-content: center;
  }
  .card-img-top {
    height: 450px;
  }
  .card-footer {
    position: absolute;
    bottom: 0;
    left: 0;
    right: 0;
    padding: 8px;
  }
  .pagination > li > a {
    color: crimson;
    background-color: #f8f9fa;
  }
  .pagination > li > a:focus,
  .pagination > li > a:hover,
  .pagination > li > span:focus,
  .pagination > li > span:hover{
    color: crimson;
  }
  .page-item:first-child .page-link,
  .page-item:last-child .page-link{
    color: crimson;
    background-color: #f8f9fa;
  }
  .page-item.active .page-link {
    z-index: 1;
    color: #f8f9fa;
    background-color: crimson;
    border-color: crimson;
  }
</style>
{% endblock %}

{% block title %} 모든 장르 {% endblock %}


{% block content %}
  <div class="container mb-3">
    <div class="row">
      <h1 class="my-3 py-3 col-12 text-center">영화</h1>
      <div class="col-3 pl-0">
        <select id="sort-select" class="mb-3 form-control" onchange="location = this.value;">
          <option class="sort-date" value="?sort=rel">최신순</option>
          <option class="sort-vote" value="?sort=vote">평점순</option>
          <option class="sort-pop" value="?sort=pop">흥행순</option>
          <option class="sort-likes" value="?sort=likes">좋아요순</option>
        </select>
      </div>
      <div class="col-9"></div>
      <div class="list-group col-3">
        {% if genre_on %}
        <a href="{% url 'movies:movie_all' %}" class="text-decoration-none"><button type="button" class="list-group-item list-group-item-action" style="background: #f8f9fa; color: #424242;">
          모든 영화
        </button></a>
        {% else %}
        <a href="{% url 'movies:movie_all' %}" class="text-decoration-none"><button type="button" class="list-group-item list-group-item-action text-light" style="background: crimson;">
          모든 영화
        </button></a>
        {% endif %}
        {% for genre in genres %}
        {% if genre.pk != 99 %}
          {% if genre_on.pk != genre.pk %}
            <a href="{% url 'movies:genre_detail' genre.pk %}" class="text-decoration-none"><button type="button" class="list-group-item list-group-item-action" style="background: #f8f9fa; color: #424242;">{{ genre.name }}</button></a>
          {% else %}
            <a href="{% url 'movies:genre_detail' genre.pk %}" class="text-decoration-none"><button type="button" class="list-group-item list-group-item-action text-light" style="background: crimson;">{{ genre.name }}</button></a>
          {% endif %}
        {% endif %}
        {% endfor %}
      </div>
      <div class="col-9 pr-0">
        <div class="row">
          {% for movie in page_obj %}
            <div class="col-4 mb-3">
              <div class="card h-100" style="background: #f8f9fa;">
                <a href="{% url 'movies:movie_detail' movie.pk %}" class="text-decoration-none text-dark">
                  <img src="https://image.tmdb.org/t/p/w780/{{movie.poster_path}}" class="card-img-top" alt="영화 포스터 이미지">
                  <div class="card-body">
                    <h5 class="card-title" style=" color: #424242;">{{ movie.title }}</h5>
                    {% for genre in movie.genres.all|slice:":1" %}
                    <p class="card-text" style=" color: #424242;">{{ genre.name }}</p>
                    {% endfor %}
                    <p class="card-text" style=" color: #424242;">{{ movie.vote_average }}</p>
                    <p class="card-text" style=" color: #424242;">{{ movie.release_date }}</p>
                  </div>
                  <br>
                  <br>
                </a>
                <div class="card-footer">
                  <h5 class="mb-0"><div class="d-flex justify-content-between">{% if request.user in movie.like_users.all %}<i class="fas fa-heart text-danger like-button" data-id="{{movie.pk}}" style="cursor: pointer;"></i>{% else %}<i class="far fa-heart text-danger like-button" data-id="{{movie.pk}}" style="cursor: pointer;"></i>{% endif %}<a id="li{{movie.pk}}ke">{{movie.like_count}} 명이 좋아합니다</a></div></h5>
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
  {% bootstrap_paginate page_obj range=10 show_prev_next="false" show_first_last="true" %}
  <div class="pagination justify-content-center mb-3">
    <span class="current text-light">
      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
    </span>
</div>
{% endblock %}

{% block js %}
<script>
  const likeButtons = document.querySelectorAll('.like-button')
  likeButtons.forEach(function(likeButton) {
    likeButton.addEventListener('click', function(event) {
      const movieId = event.target.dataset.id
      // 배포시 수정
      axios.get("{% url 'movies:movie_like' 1234 %}".replace(1234,movieId))
      .then(res => {
        if (res.data.logined) {
          if (res.data.like) {
            event.target.className = 'fas fa-heart text-danger like-button'
            const likeA = document.querySelector(`#li${movieId}ke`)
            likeA.innerText = `${res.data.like_people} 명이 좋아합니다 `
          } else {
            event.target.className = 'far fa-heart text-danger like-button'
            const likeA = document.querySelector(`#li${movieId}ke`)
            likeA.innerText = `${res.data.like_people} 명이 좋아합니다 `
          }
        } else { alert('로그인을 해주세요 ')}
      })
      .catch(err => {console.log(err)})
    })
  })

  // get url query string
  var getUrlParameter = function getUrlParameter(sParam) {
    var sPageURL = decodeURIComponent(window.location.search.substring(1)),
        sURLVariables = sPageURL.split('&'),
        sParameterName,
        i;

    for (i = 0; i < sURLVariables.length; i++) {
        sParameterName = sURLVariables[i].split('=');

        if (sParameterName[0] === sParam) {
            return sParameterName[1] === undefined ? true : sParameterName[1];
        }
    }
  };
  // 정렬방식 셀렉트 박스 유지
  $(document).ready(function(){
    var sort = getUrlParameter('sort');
    if(sort == 'likes'){
      $('.sort-likes').prop('selected', 'selected')
    }else if(sort == 'pop'){
      $('.sort-pop').prop('selected', 'selected')
    }else if(sort == 'vote') {
      $('.sort-vote').prop('selected', 'selected')
    }else {
      $('.sort-date').prop('selected', 'selected')
    }
  });
</script>
{% endblock %}

movies/templates/movies/search.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %}검색 결과{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-6 text-center">
      <h1 class="text-light">영화 검색 결과 입니다</h1>
      <table class="table table-hover table-striped table-light w-100">
        <thead>
          <tr>
            <th scope="col">No.</th>
            <th scope="col">영화 제목</th>
            <th scope="col">평론가 평점</th>
            <th scope="col">상세정보</th>
          </tr>
        </thead>
        <tbody>
          {% for movie in movies %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ movie.title }}</td>
            <td>{{ movie.vote_average}}</td>
            <td><a class="btn btn-outline-dark" href="{% url 'movies:movie_detail' movie.pk %}">상세정보</a></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <div class="col-6 text-center">
        <h1 class="text-light">게시글 검색 결과 입니다</h1>
        <table class="table table-hover table-dark w-100">
          <thead>
            <tr>
              <th scope="col">No.</th>
              <th scope="col">영화 제목</th>
              <th scope="col">게시글 제목</th>
              <th scope="col">작성자</th>
            </tr>
          </thead>
          <tbody>
            {% for article in articles %}
            <tr>
              <th scope="row"><a class="text-light">{{ forloop.counter }}</a></th>
              <td><a href="{% url 'movies:article_detail' article.pk %}" class="text-decoration-none text-light"> {{ article.movie.title }} </a></td>
              <td><a href="{% url 'movies:article_detail' article.pk %}" class="text-decoration-none text-light"> {{ article.title }} </a></td>
              <td><a class="text-light">{{ article.user }}</a></td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
  </div>
</div>
{% endblock %}