accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'), # 회원가입
    path('login/', views.login, name='login'), # 로그인
    path('logout/', views.logout, name='logout'), # 로그아웃
    path('profile/<int:user_pk>/', views.profile, name='profile'), # 내 프로필 보기
]

final_pjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('movies.urls')),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('all/', views.movie_all, name='movie_all'),  # 영화 리스트
    path('search/', views.search, name='search'), # 검색 기능
    path('community/', views.article_list, name='article_list'),  # 게시판 (모든 글 리스트)
    path('<int:movie_pk>/', views.movie_detail, name='movie_detail'),  # 영화 디테일이자 해당 영화와 관련된 글 리스트
    path('<int:movie_pk>/like/', views.movie_like, name='movie_like'), # 영화 좋아요 버튼
    path('<int:movie_pk>/create/', views.article_create, name='article_create'),  # 글 작성
    path('articles/<int:article_pk>/', views.article_detail, name='article_detail'),  # 글 디테일이자 댓글 리스트
    path('articles/<int:article_pk>/delete/', views.article_delete, name='article_delete'),  # 글 삭제
    path('articles/<int:article_pk>/update/', views.article_update, name='article_update'),  # 글 수정
    path('articles/<int:article_pk>/create/', views.comment_create, name='comment_create'),  # 댓글 작성
    path('<int:article_pk>/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),  # 댓글 삭제
    path('genres/',views.genre_all,name='genre_all'), # 모든 장르
    path('genres/<int:genre_pk>/',views.genre_detail, name='genre_detail'), # 특정 장르
    path('recommend/',views.recommend,name='recommend'), # 추천
    path('recommend/random/',views.recommend_random,name='recommend_random'), # 랜덤 추천
    path('recommend/<int:genre_pk>/', views.recommend_genre, name='recommend_genre'), # 결과로 나온 장르에서 영화 고르기
    path('worldcup/',views.worldcup,name='worldcup'), # 월드컵
    path('worldcup/<int:genre_pk>/<int:round_num>/', views.start_worldcup, name='start_worldcup'), # 월드컵 데이터 가져오기
    path('victory/<int:movie_pk>/',views.victory,name='victory'), # 월드컵 우승 올리기
    path('now/',views.movie_now,name='movie_now'), # 지금 상영작
    path('upcoming/',views.movie_upcoming,name='movie_upcoming'), # 상영 예정작
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
class User(AbstractUser):
    pass

movies/models.py
from django.db import models
from django.conf import settings
# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=100)

class Movie(models.Model):
    poster_path = models.TextField()
    adult = models.BooleanField()
    overview = models.TextField()
    release_date = models.DateField()
    genres = models.ManyToManyField(Genre,related_name='movies')
    original_title = models.CharField(max_length=300)
    original_language = models.CharField(max_length=20)
    title = models.CharField(max_length=500)
    backdrop_path = models.TextField()
    popularity = models.FloatField()
    vote_count = models.IntegerField()
    video = models.BooleanField()
    vote_average = models.FloatField()
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_movies')
    world_cup = models.IntegerField(default=0)

class Article(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    rank = models.IntegerField(default=10)
    title = models.CharField(max_length=200)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username',)

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth import login as auth_login, logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm
from .forms import CustomUserCreationForm
# Create your views here.
User = get_user_model()
def signup(request):
    if request.user.is_authenticated:
        messages.warning(request,'로그인 상태입니다. 로그아웃하고 이용해주세요! 😁')
        return redirect('movies:index')
    else:
        if request.method == 'POST':
            form = CustomUserCreationForm(request.POST)
            if form.is_valid():
                user = form.save()
                auth_login(request,user,backend='django.contrib.auth.backends.ModelBackend')
                return redirect('movies:index')
        else:
            form = CustomUserCreationForm()
        context = {'form': form}
        return render(request,'accounts/signup.html',context)

def login(request):
    if request.user.is_authenticated:
        messages.warning(request, '이미 로그인이 된 상태입니다. 즐겁게 이용해주세요 😊')
        return redirect('movies:index')
    else:
        if request.method == 'POST':
            form = AuthenticationForm(request, request.POST)
            if form.is_valid():
                auth_login(request,form.get_user())
                return redirect('movies:index')
        else:
            form = AuthenticationForm()
        context = {'form':form}
        return render(request,'accounts/login.html',context)

def logout(request):
    if request.user.is_anonymous:
        messages.error(request,'로그인을 안 하셨는데 로그아웃이라뇨! 농담두~ 😋')
    else:
        messages.success(request,'로그아웃이 되었습니다! 또 찾아와주세요!')
        auth_logout(request)
    return redirect('movies:index')

def profile(request,user_pk):
    if request.user.pk != user_pk:
        messages.error(request,'남의 프로필을 보진 말아주세요! 👿')
        return redirect('movies:index')
    else:
        user = get_object_or_404(User,pk=user_pk)
        context = {
            'user': user
        }
        return render(request,'accounts/profile.html',context)

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load socialaccount %}

{% block title %}로그인을 부탁드립니다{% endblock %}

{% block content %}
<div class="container">
  <h1 class="mt-5 text-center text-light">login</h1>
  <hr>
  <form action="" method="POST" class="text-light">
    {% csrf_token %}
    {% bootstrap_form form %}
    <div class="d-flex justify-content-end">
      <button class="btn btn-success">로그인</button>
    </div>
    <div class="text-center mt-4">
    <a class="text-light mb-3">구글 또는 카카오 계정이 있으신가요?</a><br>
    <a class="text-white btn btn-primary mr-3 my-3" href="{% provider_login_url 'google' %}">구글 계정으로 로그인</a>
    <a href="{% provider_login_url 'kakao' %}" class="text-white btn btn-warning my-3">카카오 계정으로 로그인</a>
    </div>
  </form>
</div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block css %}
<style>
  h1 {
    font-family: 'Gugi', cursive;
    color: crimson;
  }
  .username {
    color: #00b992;
  }
  .hello {
    background-color: rgb(45, 45, 45);
  }
  thead {
    background-color: #424242;
  }
  tbody {
    background-color: gray;
  }
</style>
{% endblock %}

{% block title %} {{user.username}}님의 프로필 {% endblock %}

{% block content %}
<div class="container text-center">
  <div class="my-3 py-3 hello">
    <h1 class="d-inline username">{{user.username}}</h1><h1 class="d-inline">님, 안녕하세요!</h1>
  </div>
  <!-- <div class="row">
    <div class="col-6">
      <h3 class="text-light">최근에 좋아요를 누른 영화</h3>
      <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          {% for movie in user.like_movies.all|slice:":10" %}
          {% if forloop.counter0 == 0%}
          <li data-target="#carouselExampleIndicators" data-slide-to="{{ forloop.counter0}}" class="active"></li>
          {% else %}
          <li data-target="#carouselExampleIndicators" data-slide-to="{{ forloop.counter0}}"></li>
          {% endif %}
          {% endfor %}
        </ol>
        <div class="carousel-inner">
          {% for movie in user.like_movies.all %}
          {% if forloop.counter0 == 0%}
          <div class="carousel-item active">
            <img class="d-block w-100" src="https://image.tmdb.org/t/p/w780/{{movie.backdrop_path}}">
            <div class="carousel-caption d-none d-md-block" style="font-weight: bold; background-color: #ffffff; background-color: rgba(0, 0, 0, 0.5);">
              <h5><a class="text-decoration-none text-light" href="{% url 'movies:movie_detail' movie.pk %}">{{ movie.title }}</a></h5>
            </div>
          </div>
          {% else %}
          <div class="carousel-item">
            <img class="d-block w-100" src="https://image.tmdb.org/t/p/w780/{{movie.backdrop_path}}">
            <div class="carousel-caption d-none d-md-block" style="font-weight: bold; background-color: #ffffff; background-color: rgba(0, 0, 0, 0.5);">
              <h5><a class="text-decoration-none text-light" href="{% url 'movies:movie_detail' movie.pk %}">{{ movie.title }}</a></h5>
            </div>
          </div>
          {% endif %}
          {% endfor %}
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
    <div class="col-6">
      <h3 class="text-light">최근에 작성한 글</h3>
      <table class="table table-dark">
        <thead>
          <tr>
            <th scope="col">No.</th>
            <th scope="col">게시글 제목</th>
            <th scope="col">영화 제목</th>
          </tr>
        </thead>
        <tbody>
          {% for article in user.article_set.all|slice:":10" %}
          <tr>
            <th scope="row">{{ article.pk }}</th>
            <td><a class="text-decoration-none text-light" href="{% url 'movies:article_detail' article.pk %}">{{ article.title }}</a></td>
            <td><a class="text-decoration-none text-light" href="{% url 'movies:movie_detail' article.movie.pk%}">{{ article.movie.title }}</a></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div> -->
  <h2 class="mt-5 mb-4 text-light">최근에 좋아요를 누른 영화</h2>
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      {% for movie in user.like_movies.all|slice:":10" %}
      {% if forloop.counter0 == 0%}
      <li data-target="#carouselExampleIndicators" data-slide-to="{{ forloop.counter0}}" class="active"></li>
      {% else %}
      <li data-target="#carouselExampleIndicators" data-slide-to="{{ forloop.counter0}}"></li>
      {% endif %}
      {% endfor %}
    </ol>
    <div class="carousel-inner">
      {% for movie in user.like_movies.all %}
      {% if forloop.counter0 == 0%}
      <div class="carousel-item active">
        <img class="d-block w-100" src="https://image.tmdb.org/t/p/w780/{{movie.backdrop_path}}">
        <div class="carousel-caption d-none d-md-block" style="font-weight: bold; background-color: #ffffff; background-color: rgba(0, 0, 0, 0.5);">
          <h5><a class="text-decoration-none text-light" href="{% url 'movies:movie_detail' movie.pk %}">{{ movie.title }}</a></h5>
        </div>
      </div>
      {% else %}
      <div class="carousel-item">
        <img class="d-block w-100" src="https://image.tmdb.org/t/p/w780/{{movie.backdrop_path}}">
        <div class="carousel-caption d-none d-md-block" style="font-weight: bold; background-color: #ffffff; background-color: rgba(0, 0, 0, 0.5);">
          <h5><a class="text-decoration-none text-light" href="{% url 'movies:movie_detail' movie.pk %}">{{ movie.title }}</a></h5>
        </div>
      </div>
      {% endif %}
      {% endfor %}
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
  <h2 class="mt-5 mb-4 text-light">최근에 작성한 글</h2>
  <table class="table">
    <thead>
      <tr>
        <th scope="col" class="text-light">No.</th>
        <th scope="col" class="text-light">게시글 제목</th>
        <th scope="col" class="text-light">영화 제목</th>
      </tr>
    </thead>
    <tbody>
      {% for article in user.article_set.all %}
      <tr>
        <th scope="row" class="text-light">{{ article.pk }}</th>
        <td><a class="text-decoration-none text-light" href="{% url 'movies:article_detail' article.pk %}">{{ article.title }}</a></td>
        <td><a class="text-decoration-none text-light" href="{% url 'movies:movie_detail' article.movie.pk%}">{{ article.movie.title }}</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %} 회원가입 {% endblock %}

{% block content %}
<div class="container">
  <h1 class="mt-5 text-center text-light">회원가입을 해주세요!</h1>
  <hr>
  <form action="" method="POST" class="text-light">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button class="btn btn-success">회원가입하기</button>
  </form>
</div>
{% endblock %}