accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'), # 회원가입
    path('login/', views.login, name='login'), # 로그인
    path('logout/', views.logout, name='logout'), # 로그아웃
    path('profile/<int:user_pk>/', views.profile, name='profile'), # 내 프로필 보기
]

final_pjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('movies.urls')),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('all/', views.movie_all, name='movie_all'),  # 영화 리스트
    path('search/', views.search, name='search'), # 검색 기능
    path('community/', views.article_list, name='article_list'),  # 게시판 (모든 글 리스트)
    path('<int:movie_pk>/', views.movie_detail, name='movie_detail'),  # 영화 디테일이자 해당 영화와 관련된 글 리스트
    path('<int:movie_pk>/like/', views.movie_like, name='movie_like'), # 영화 좋아요 버튼
    path('<int:movie_pk>/create/', views.article_create, name='article_create'),  # 글 작성
    path('articles/<int:article_pk>/', views.article_detail, name='article_detail'),  # 글 디테일이자 댓글 리스트
    path('articles/<int:article_pk>/delete/', views.article_delete, name='article_delete'),  # 글 삭제
    path('articles/<int:article_pk>/update/', views.article_update, name='article_update'),  # 글 수정
    path('articles/<int:article_pk>/create/', views.comment_create, name='comment_create'),  # 댓글 작성
    path('<int:article_pk>/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),  # 댓글 삭제
    path('genres/',views.genre_all,name='genre_all'), # 모든 장르
    path('genres/<int:genre_pk>/',views.genre_detail, name='genre_detail'), # 특정 장르
    path('recommend/',views.recommend,name='recommend'), # 추천
    path('recommend/random/',views.recommend_random,name='recommend_random'), # 랜덤 추천
    path('recommend/<int:genre_pk>/', views.recommend_genre, name='recommend_genre'), # 결과로 나온 장르에서 영화 고르기
    path('worldcup/',views.worldcup,name='worldcup'), # 월드컵
    path('worldcup/<int:genre_pk>/<int:round_num>/', views.start_worldcup, name='start_worldcup'), # 월드컵 데이터 가져오기
    path('victory/<int:movie_pk>/',views.victory,name='victory'), # 월드컵 우승 올리기
    path('now/',views.movie_now,name='movie_now'), # 지금 상영작
    path('upcoming/',views.movie_upcoming,name='movie_upcoming'), # 상영 예정작
]

templates/base.html
{% load static %}
<!DOCTYPE html>
{% load bootstrap4 %}
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% bootstrap_css %}
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css" integrity="sha384-Bfad6CLCknfcloXFOyFnlgtENryhrpZCe29RTifKEixXQZ38WheV+i/6YWSzkz3V" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css2?family=Gugi&display=swap" rel="stylesheet">
  <style>
    @font-face { font-family: 'SeoulNamsanM'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_two@1.0/SeoulNamsanM.woff') format('woff'); font-weight: normal; font-style: normal; }
    body {
      font-family: 'SeoulNamsanM';
      background: rgb(37, 38, 38);
    }
    .dropdown-item:hover {
      background-color: rgb(70, 70, 70);
    }
    nav {
      background-color: rgb(60, 60, 60);
    }
    .btn {
      outline-color: crimson;
    }
    .danger {
      border-color: crimson;
      color: crimson;
    }
    .danger:hover {
      background: crimson;
      color: white;
    }
    .topbutton {
      position: fixed;
      right: 30px ;
      bottom: 30px;
      padding: 3px 7.5px;
      z-index: 1;
    }
    .dropdown-menu {
      background-color: rgb(60, 60, 60);
    }
  </style>
  {% block css %}
  {% endblock %}
  <title>{% block title %}{% endblock %}</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark justify-content-between sticky-top">
    <a class="navbar-brand d-flex align-items-center" href="{% url 'movies:index' %}" style="color: #7fffd4;"><img id="logo" src="{% static 'logo.png' %}" height="35"><span class="d-inline-block ml-2 eunguen" style="font-family: 'Gugi', cursive;">EUNGEUN Movie</span></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link active" href="{% url 'movies:index' %}"> 메인 화면 <span class="sr-only">(current)</span></a>
        <div class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="listDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          카테고리
          </a>
          <div class="dropdown-menu" aria-labelledby="listDropdown">
            <a class="dropdown-item text-light" href="{% url 'movies:movie_all' %}">모든 영화</a>
            <a class="dropdown-item text-light" href="{% url 'movies:article_list' %}">모든 게시글</a>
          </div>
        </div>
        <div class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            다양한 기능
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item text-light" href="{% url 'movies:recommend' %}">영화 추천</a>
            <a class="dropdown-item text-light" href="{% url 'movies:worldcup' %}">영화 월드컵</a>
          </div>
        </div>
        <div class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            극장
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item text-light" href="{% url 'movies:movie_now' %}">현재 상영작</a>
            <a class="dropdown-item text-light" href="{% url 'movies:movie_upcoming' %}">개봉 예정작</a>
          </div>
      </div>
    </div>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <form class="form-inline my-2 my-lg-0" action="{% url 'movies:search' %}" method="POST">
          {% csrf_token %}
          <input class="form-control mr-sm-2" name="search_value" placeholder="검색어를 입력하세요">
          <button class="btn danger">검색하기</button>
        </form>
        {% if request.user.is_authenticated %}
        <a class="nav-item nav-link pl-3" href="{% url 'accounts:profile' request.user.pk %}">프로필</a>
        <a class="nav-item nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
        {% else %}
        <a class="nav-item nav-link pl-3" href="{% url 'accounts:login'%}">로그인</a>
        <a class="nav-item nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
        {% endif %}
      </div>
    </div>
  </nav>
  {% if messages %}
    {% for message in messages %}
    <div {% if message.tags %} class="alert alert-{{ message.tags }} text-center"{% endif %}>{{ message }}</div>
    {% endfor %}
  {% endif %}
  <button class="topbutton btn btn-warning" onclick="window.scrollTo(0,0);">▲</button>
  {% block content %}
  {% endblock %}

  {% bootstrap_javascript jquery='full' %}
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  {% block js %}
  {% endblock %}
</body>
</html>