final_pjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('movies.urls')),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('all/', views.movie_all, name='movie_all'),  # 영화 리스트
    path('search/', views.search, name='search'), # 검색 기능
    path('community/', views.article_list, name='article_list'),  # 게시판 (모든 글 리스트)
    path('<int:movie_pk>/', views.movie_detail, name='movie_detail'),  # 영화 디테일이자 해당 영화와 관련된 글 리스트
    path('<int:movie_pk>/like/', views.movie_like, name='movie_like'), # 영화 좋아요 버튼
    path('<int:movie_pk>/create/', views.article_create, name='article_create'),  # 글 작성
    path('articles/<int:article_pk>/', views.article_detail, name='article_detail'),  # 글 디테일이자 댓글 리스트
    path('articles/<int:article_pk>/delete/', views.article_delete, name='article_delete'),  # 글 삭제
    path('articles/<int:article_pk>/update/', views.article_update, name='article_update'),  # 글 수정
    path('articles/<int:article_pk>/create/', views.comment_create, name='comment_create'),  # 댓글 작성
    path('<int:article_pk>/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),  # 댓글 삭제
    path('genres/',views.genre_all,name='genre_all'), # 모든 장르
    path('genres/<int:genre_pk>/',views.genre_detail, name='genre_detail'), # 특정 장르
    path('recommend/',views.recommend,name='recommend'), # 추천
    path('recommend/random/',views.recommend_random,name='recommend_random'), # 랜덤 추천
    path('recommend/<int:genre_pk>/', views.recommend_genre, name='recommend_genre'), # 결과로 나온 장르에서 영화 고르기
    path('worldcup/',views.worldcup,name='worldcup'), # 월드컵
    path('worldcup/<int:genre_pk>/<int:round_num>/', views.start_worldcup, name='start_worldcup'), # 월드컵 데이터 가져오기
    path('victory/<int:movie_pk>/',views.victory,name='victory'), # 월드컵 우승 올리기
    path('now/',views.movie_now,name='movie_now'), # 지금 상영작
    path('upcoming/',views.movie_upcoming,name='movie_upcoming'), # 상영 예정작
]

movies/models.py
from django.db import models
from django.conf import settings
# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=100)

class Movie(models.Model):
    poster_path = models.TextField()
    adult = models.BooleanField()
    overview = models.TextField()
    release_date = models.DateField()
    genres = models.ManyToManyField(Genre,related_name='movies')
    original_title = models.CharField(max_length=300)
    original_language = models.CharField(max_length=20)
    title = models.CharField(max_length=500)
    backdrop_path = models.TextField()
    popularity = models.FloatField()
    vote_count = models.IntegerField()
    video = models.BooleanField()
    vote_average = models.FloatField()
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_movies')
    world_cup = models.IntegerField(default=0)

class Article(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    rank = models.IntegerField(default=10)
    title = models.CharField(max_length=200)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

movies/forms.py
from django import forms
from .models import Article, Comment

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'rank', 'content']
        widgets = {
            'title' : forms.TextInput(attrs={'class':'col-12 form-control', 'placeholder': '리뷰제목을 입력해주세요'}),
            'rank': forms.Select(choices=[[i,i] for i in range(0,11)]),
            'content' : forms.Textarea(attrs={'class':'col-12 form-control', 'placeholder':'내용을 입력해주세요','cols':100, 'rows':10})
        }
        labels = {
            'title': ('리뷰 제목'),
            'rank': ('별점'),
            'content': ('내용'),
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content': forms.Textarea(attrs={'placeholder': '댓글을 입력해주세요!', 'rows':3})
        }
        labels = {
            'content': ('')
        }

movies/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.conf import settings
from django.http import JsonResponse
from django.core.paginator import Paginator
from django.db.models import Count, Q
from django.contrib import messages
from .models import Movie, Genre, Article, Comment
from .forms import ArticleForm, CommentForm
import requests
import random

# Create your views here.
def index(request):
    api_key = settings.TMDB_KEY
    data = requests.get('https://api.themoviedb.org/3/movie/now_playing?api_key='+api_key+'&language=ko-KR&page=1&region=KR').json()
    recommend_movies = data['results'][:10]
    pop_movies = Movie.objects.exclude(id=664413).order_by('-popularity')[:6]
    vote_movies = Movie.objects.exclude(id=664413).order_by('-vote_average')[:6]
    articles = Article.objects.order_by('-pk')[:10]
    users_movies = Movie.objects.annotate(q_count=Count('like_users')).order_by('-q_count')[:6]
    random_movie = requests.get('https://api.themoviedb.org/3/movie/upcoming?api_key='+api_key+'&language=ko-KR&page=1&region=KR').json()
    random_movie = random.choice(random_movie['results'])
    api_key = settings.API_SECRET_KEY
    context = {
        'recommend_movies': recommend_movies,
        'pop_movies': pop_movies,
        'vote_movies': vote_movies,
        'articles': articles,
        'users_movies': users_movies,
        'random_movie': random_movie,
        'api_key': api_key
    }
    return render(request,'movies/index.html',context)

def search(request):
    if request.method == 'POST':
        search_value = request.POST['search_value']
        if search_value == '':
            messages.warning(request,'검색창에 검색어를 입력해주세요!')
            return redirect('movies:index')
        else:
            movies = Movie.objects.filter(title__contains=search_value).distinct()
            articles = Article.objects.filter(Q(title__contains=search_value)|Q(content__contains=search_value)).distinct()
            context = {
                'movies': movies,
                'articles': articles
            }
            return render(request,'movies/search.html',context)
    else:
        messages.warning(request,'검색창을 이용해주세요! 💻')
        return redirect('movies:index')

def movie_all(request):
    sort = request.GET.get('sort','')
    if sort == 'vote':
        movies = Movie.objects.annotate(like_count=Count('like_users')).order_by('-vote_average')
    elif sort == 'pop':
        movies = Movie.objects.annotate(like_count=Count('like_users')).order_by('-popularity')
    elif sort == 'likes':
        movies = Movie.objects.annotate(like_count=Count('like_users')).order_by('-like_count')
    else:
        movies = Movie.objects.annotate(like_count=Count('like_users')).order_by('-release_date')
    genres = Genre.objects.order_by('name')
    paginator = Paginator(movies, 12)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'movies': movies,
        'genres': genres,
        'page_obj': page_obj,
    }
    return render(request,'movies/movie_all.html', context)

def article_list(request):
    articles = Article.objects.order_by('-pk')
    paginator = Paginator(articles,20)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'articles': articles,
        'page_obj': page_obj
    }
    return render(request,'articles/article_all.html',context)

def movie_detail(request, movie_pk):
    movie = get_object_or_404(Movie.objects.annotate(like_count=Count('like_users')).prefetch_related('article_set'),pk=movie_pk)
    api_key = settings.API_SECRET_KEY
    tmdb_key = settings.TMDB_KEY
    score = 0
    people = 0
    for i in movie.article_set.all():
        score += i.rank
        people += 1
    if people == 0:
        avg_rank = None
    else:
        avg_rank = round(score/people,1)
    context = {
        'movie': movie,
        'api_key': api_key,
        'avg_rank': avg_rank,
        'tmdb_key': tmdb_key
    }
    return render(request, 'movies/movie_detail.html', context)

def movie_like(request, movie_pk):
    if request.user.is_authenticated:
        movie = get_object_or_404(Movie,pk=movie_pk)
        logined = True
        if movie.like_users.filter(id=request.user.pk).exists():
            like = False
            movie.like_users.remove(request.user)
            like_people = len(movie.like_users.all())
        else:
            like = True
            movie.like_users.add(request.user)
            like_people = len(movie.like_users.all())
    else:
        logined = False
        like = False
        like_people = 0
    return JsonResponse({'logined':logined,'like':like,'like_people':like_people})

def article_create(request, movie_pk):
    if request.user.is_anonymous:
        messages.warning(request,'로그인을 해주세요 🙇')
        return redirect('accounts:login')
    else:
        if request.method == 'POST':
            form = ArticleForm(request.POST)
            if form.is_valid():
                movie = get_object_or_404(Movie,pk=movie_pk)
                article = form.save(commit=False)
                article.user = request.user
                article.movie = movie
                article.save()
                return redirect('movies:article_detail', article.pk)
        else:
            form = ArticleForm()
        context = {'form':form}
        return render(request,'articles/create.html',context)

def article_detail(request, article_pk):
    article = get_object_or_404(Article.objects.prefetch_related('comment_set'),pk=article_pk)
    form = CommentForm()
    context = {
        'article': article,
        'form': form
    }
    return render(request,'articles/detail.html',context)

def article_delete(request, article_pk):
    if request.user.is_anonymous:
        messages.warning(request,'이런 로그인을 깜빡하셨군요 😋')
        return redirect('accounts:login')
    article = get_object_or_404(Article,pk=article_pk)
    if request.user != article.user:
        messages.error(request,'다른 유저의 글은 삭제 못해요! 😡')
        return redirect('movies:article_detail',article.pk)
    else:
        if request.method == 'POST':
            article.delete()
            messages.success(request,'성공적으로 삭제 되었습니다! 👍')
            return redirect('movies:index')
        else:
            messages.error(request,'지정한 방식으로 삭제를 부탁드립니다 😭')
            return redirect('movies:article_detail',article.pk)


def article_update(request, article_pk):
    if request.user.is_anonymous:
        messages.warning(request,'이런 로그인을 깜빡하셨군요 😋')
        return redirect('accounts:login')
    article = get_object_or_404(Article,pk=article_pk)
    if article.user != request.user:
        messages.error(request,'다른 유저의 글은 수정할 수가 없습니다! 👿')
        return redirect('movies:article_detail',article.pk)
    else:
        if request.method == 'POST':
            form = ArticleForm(request.POST, instance=article)
            if form.is_valid():
                form.save()
                return redirect('movies:article_detail',article.pk)
        else:
            form = ArticleForm(instance=article)
        context = {'form': form }
        return render(request,'articles/create.html',context)

def comment_create(request, article_pk):
    if request.user.is_anonymous:
        messages.error(request,'로그인을 하고 댓글을 써주시길 바랍니다. 😇')
        return redirect('accounts:login')
    else:
        if request.method == 'POST':
            article = get_object_or_404(Article,pk=article_pk)
            form = CommentForm(request.POST)
            if form.is_valid():
                comment = form.save(commit=False)
                comment.user = request.user
                comment.article = article
                comment.save()
                return redirect('movies:article_detail', article.pk)
        else:
            messages.error(request,'댓글작성은 어떻게 들어오셨나요? 🤔')
            return redirect('movies:article_detail', article.pk)

def comment_delete(request, article_pk, comment_pk):
    if request.user.is_anonymous:
        messages.warning(request,'로그인을 하고 댓글삭제를 요청해주세요! 😵')
        return redirect('movies:article_detail',article_pk)
    comment = get_object_or_404(Comment, pk=comment_pk)
    if comment.user != request.user:
        messages.error(request,'남의 댓글은 삭제하실 수가 없는데 뭘 하시는 거죠? 🤔')
        return redirect('movies:article_detail',article_pk)
    else:
        if request.method == 'POST':
            comment.delete()
            messages.success(request,'성공적으로 댓글이 삭제되었습니다!')
        else:
            messages.warning(request,'정해진 방식으로 요청을 보내주세요! 😟')
        return redirect('movies:article_detail',article_pk)

def genre_all(request):
    genres = Genre.objects.all()
    context = {
        'genres': genres
    }
    return render(request,'movies/genre_all.html',context)

def genre_detail(request,genre_pk):
    genre_on = get_object_or_404(Genre,pk=genre_pk)
    sort = request.GET.get('sort','')
    if sort == 'vote':
        movies =  genre_on.movies.annotate(like_count=Count('like_users')).order_by('-vote_average')
    elif sort == 'pop':
        movies =  genre_on.movies.annotate(like_count=Count('like_users')).order_by('-popularity')
    elif sort == 'likes':
        movies =  genre_on.movies.annotate(like_count=Count('like_users')).order_by('-like_count')
    else:
        movies =  genre_on.movies.annotate(like_count=Count('like_users')).order_by('-release_date')
    paginator = Paginator(movies, 12)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    genres = Genre.objects.order_by('name')
    context = {
        'movies': movies,
        'page_obj': page_obj,
        'genres': genres,
        'genre_on': genre_on
    }
    return render(request,'movies/movie_all.html', context)

def recommend(request):
    weather_key = settings.WEATHER_KEY
    genres = Genre.objects.all()
    context = {
        'weather_key': weather_key,
        'genres': genres
    }

movies/templates/articles/article_all.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load bootstrap_pagination %}

{% block css %}
  <style>
    h1 {
    font-family: 'Gugi', cursive; 
    color: crimson;
    background-color: #f8f9fa;
    }
    ul.pagination {
      justify-content: center;
    }
    thead {
      background-color: #424242;
    }
    tbody {
      background-color: gray;
    }
    .pagination > li > a {
    color: crimson;
    background-color: #f8f9fa;
    }
    .pagination > li > a:focus,
    .pagination > li > a:hover,
    .pagination > li > span:focus,
    .pagination > li > span:hover{
      color: crimson;
    }
    .page-item:first-child .page-link,
    .page-item:last-child .page-link{
      color: crimson;
      background-color: #f8f9fa;
    }
    .page-item.active .page-link {
      z-index: 1;
      color: #f8f9fa;
      background-color: crimson;
      border-color: crimson;
    }
  </style>
{% endblock %}

{% block title %} 모든 게시글 {% endblock %}

{% block content %}
<div class="container mb-3">
  <div class="row">
    <h1 class="my-3 py-3 col-12 text-center">커뮤니티</h1>
    <table class="table table-hover col-12">
      <thead>
        <tr>
          <th scope="col" class="text-light">No.</th>
          <th scope="col" class="text-light">글 제목</th>
          <th scope="col" class="text-light">영화 제목</th>
          <th scope="col" class="text-light">평점</th>
          <th scope="col" class="text-light">작성자</th>
        </tr>
      </thead>
      <tbody>
        {% for article in page_obj %}
        <tr>
          <th scope="row" class="text-light">{{ article.pk }}</th>
          <td><a class="text-decoration-none text-light" href="{% url 'movies:article_detail' article.pk %}">{{ article.title }}</a></td>
          <td><a class="text-decoration-none text-light" href="{% url 'movies:movie_detail' article.movie.pk %}">{{ article.movie.title }}</a></td>
          <td><a class="text-decoration-none text-light">{{ article.rank }}</a></td>
          <td class="text-light">{{ article.user }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  {% bootstrap_paginate page_obj range=10 show_prev_next="false" show_first_last="true" %}
  <div class="pagination justify-content-center">
    <span class="step-links">
      {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
      {% endif %}
      <span class="current">
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
      </span>
      {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">next</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
      {% endif %}
    </span>
  </div>
</div>
{% endblock %}

movies/templates/articles/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %}글 작성창{% endblock %}

{% block content %}
<div class="container">
  <form action="" method="POST" class="text-light">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button class="btn btn-success">글 작성하기</button>
  </form>
</div>
{% endblock %}

movies/templates/articles/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block css %}
<style>
  hr {
    border: 1px solid white;
  }
  .information {
    padding: 3px 9px;
    font-size: 0.75rem;
  }
  .smallinfo {
    padding-left: 30px;
  }
</style>
{% endblock %}
{% block title %}{{article.title}}{% endblock %}

{% block content %}
<div class="container my-5">
  <div class="row">
    <div class="col-8">
      <h2 class="text-light">{{article.title}}</h2>
      <h4><a href="{% url 'movies:movie_detail' article.movie.pk%}" class="text-decoration-none text-light"><span class="badge badge-dark">{{article.movie.title}}</span></a></h4>
    </div>
    <div class="col-4">
      <div class="row">
        <div class="col-3">
          <img src="https://image.tmdb.org/t/p/w92/{{article.movie.poster_path}}">
        </div>
        <div class="col-9 smallinfo">
          <small class="text-light">작성 일시 : {{ article.created_at|date:"Y년 m월 d일 a f" }}</small><br>
          <small class="text-light">수정 일시 : {{ article.updated_at|date:"Y년 m월 d일 a f" }}</small><br>
          <p class="btn btn-info mt-2 information">글쓴이 평점 : <span class="badge badge-light">{{article.rank}}</span></p>
          <p><a href="{% url 'movies:movie_detail' article.movie.pk%}" class="text-decoration-none btn btn-outline-info text-light information">영화정보</a></p>
        </div>
      </div>
    </div>
  </div>
    <hr>
    <p class="text-light">
    {{article.content}}
    </p>
    <div class="row my-3">
      <div class="col-12 d-flex justify-content-end">
        <div class="mt-3">
          {% if request.user == article.user %}
          <a class="mb-2 btn btn-outline-warning text-decoration-none text-light" href="{% url 'movies:article_update' article.pk %}">수정하기</a>
          <form action="{% url 'movies:article_delete' article.pk %}" method="POST">{% csrf_token %}<button class="btn btn-outline-danger text-decoration-none text-light">삭제하기</button></form>
          {% endif %}
        </div>
      </div>
    </div>
    <hr>
    {% if request.user.is_authenticated %}
    <form action="{% url 'movies:comment_create' article.pk %}" method="POST" class="my-3">
      <h4 class="text-light">댓글 작성</h4>
      {% csrf_token %}
      {% bootstrap_form form %}
      <button class="btn btn-success btn-sm">작성</button>
    </form>
    <hr>
    {% endif %}
    {% for comment in article.comment_set.all %}
    <div class="d-flex justify-content-between">
    <p class="text-light">{{comment.content}}</p>
    {% if comment.user == request.user %}
    <form action="{% url 'movies:comment_delete' article.pk comment.pk %}" method="POST">{% csrf_token %}<button class="btn btn-danger btn-sm">삭제</button></form>
    {% else %}
    <p class="text-light">작성 시간 : {{ comment.created_at|date:"Y년 m월 d일 a f" }}</p>
    {% endif %}
    </div>
    <hr>
    {% endfor %}
</div>
{% endblock %}